### ISSUE TITLE
Optimization 中最后出现 Function failed after 5 attempts. obj sdf is None:  airplane. 是什么情况？（而且好像还是有时候出现，有时候不出现）

### ISSUE THREAD

**Issue by jinxuran** [lym29/EasyHOI#2]

**Comment by lym29** [comment]
说明重建出的mesh质量较差无法构造sdf，可以通过resample修复：
python preprocess/resample_mesh.py --data_dir ./data --resample

**Comment by jinxuran** [comment]
通过resample修复之后，还是不行，我也看了obj，确实mesh较差（是不是可以再修复？）。我看第五步 Reconstruct obj产生的mesh也较差，这是不是和输入图片有很大关联？（我不是研究HOI的🥹）

**Comment by lym29** [comment]
目前的瓶颈在物体重建的大模型上，我会更新一个tripo的接口，更新后你可以尝试一下tripo3d生成的结果
