### ISSUE TITLE
Training Time 

### ISSUE THREAD

**Issue by soberguo** [lym29/EasyHOI#3]
Great work, how long does it take to train on an A40?

**Comment by lym29** [comment]
Thanks for your interest!
It takes around 90 seconds for a single image, with optimization consuming about 60 seconds.

**Comment by soberguo** [comment]
Thanks for your reply. I noticed that the paper mentioned using a force closure tester to filter out instances where the hand and object are not in contact and randomly select 500 images from each dataset for evaluation. Could you provide specific dataset information?

**Comment by lym29** [comment]
Yes, here are the test splits for each dataset. I used absolute paths to find images, so please replace the path with your own.

[arctic_test.csv](https://github.com/user-attachments/files/18221343/arctic_test.csv)
[dexycb_test.csv](https://github.com/user-attachments/files/18221344/dexycb_test.csv)
[oakink_test.csv](https://github.com/user-attachments/files/18221345/oakink_test.csv)

**Comment by soberguo** [comment]
Thanks again for your reply. You also filtered some images in the training set. I would like to know which images were filtered out.

**Comment by soberguo** [comment]
Thank you very much, I look forward to your improved code.
