### ISSUE TITLE
Whole dataset and evaluation Code

### ISSUE THREAD

**Issue by byran-wang** [lym29/EasyHOI#7]
Hi @lym29 ：

非常感谢你的工作。

我已经在你提供的demo数据上将代码跑通了，不过没有看到论文中展示的所有数据和Evaluation code，Whole dataset 和 evaluation Code计划开源吗？

谢谢！！

**Comment by lym29** [comment]
目前提供的简单版本测试代码为： src/eval_mesh.py
后续会更新完整的evaluation code
