### ISSUE TITLE
栈溢出

### ISSUE THREAD

**Issue by 1024AILab** [lym29/EasyHOI#8]
您好，我在执行step5的时候遇到了栈溢出，如何解决啊？
![3bdb163998e47bba82c0510fcad3ecf](https://github.com/user-attachments/assets/8027667a-afc2-4b90-94f6-c04d31e9eca0)

**Comment by lym29** [comment]
GPU显存不足，建议使用20G以上的显卡

**Comment by 1024AILab** [comment]
我用的4090，没有报cuda out of memory

**Comment by lym29** [comment]
直接运行InstantMesh源码 https://github.com/TencentARC/InstantMesh/
`python run.py configs/instant-mesh-large.yaml examples/hatsune_miku.png --save_video`
会有问题吗？

**Comment by 1024AILab** [comment]
我去autodl重新配置InstantMesh环境解决了，谢谢佬
